# Generated by Django 2.1.1 on 2018-09-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=20)),
                ('sub_locality', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=6)),
                ('house_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=20)),
                ('days', models.CharField(max_length=20)),
                ('crop_diseases', models.CharField(max_length=255)),
                ('current_price', models.CharField(max_length=30)),
                ('fungicides', models.CharField(max_length=50)),
                ('herbicides', models.CharField(max_length=50)),
                ('seed_treatment', models.CharField(max_length=255)),
                ('planting_teachnique', models.TextField()),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mandi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('mandi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aadhaar', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=10)),
                ('address_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
