# Generated by Django 2.1 on 2018-09-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=20)),
                ('sub_locality', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=6)),
                ('house_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('aadhaar', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=10)),
                ('address_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
