# Generated by Django 2.1.1 on 2018-09-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0002_remove_data_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
