# Generated by Django 2.1 on 2018-09-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0003_auto_20180927_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=20)),
                ('days', models.CharField(max_length=20)),
                ('crop_diseases', models.CharField(max_length=255)),
                ('current_price', models.CharField(max_length=30)),
                ('fungicides', models.CharField(max_length=50)),
                ('herbicides', models.CharField(max_length=50)),
                ('seed_treatment', models.CharField(max_length=255)),
                ('planting_teachnique', models.TextField()),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mandi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('mandi', models.CharField(max_length=20)),
            ],
        ),
    ]
