# Generated by Django 2.1.1 on 2018-09-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0003_auto_20180929_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='aadhaar',
            new_name='password',
        ),
    ]
